### ISSUE TITLE
Public release

### ISSUE THREAD

**Issue by PlayXman** [PlayXman/app-my-spotlight#17]
## Target
Public release of the extension at "Mozilla's addon shop".

## Todo
1. Add link to addon profile and Github issues to the settings footer
1. Change build process
    1. Rename build folder to "packages".
    1. `npm run build` builds only `dist` version of project.
    1. New script `npm run generate` creates "packages" folder with zipped dist files and zip file with all sources.
1. Rewrite README.
1. Create new "public" release at addon page. And post files and sources too.
1. Fill public data (description, links, pics, screenshots).
1. Update README with download link.

## Depends on
https://github.com/PlayXman/app-startpage/milestone/1

**Comment by PlayXman** [comment]
#37

**Comment by PlayXman** [comment]
## Todo
- [x] Change build process
  1. Rename build folder to "packages"
  2. `npm run build` builds only `dist` version of project
  3. New script `npm run generate` creates "packages" folder with zipped dist files and zip file with all sources
- [x] Open-source essentials (license, issue and pull request templates)
- [x] Create new "public" release at addon page
  1. Post dist files and sources
  2. Fill public data (description, links, pics, screenshots)
- [x] App updates
  1. Add link to addon profile and Github issues to the settings footer
- [x] Rewrite README + add download link

**Comment by PlayXman** [comment]
https://addons.mozilla.org/en-US/firefox/addon/my-spotlight/
