### ISSUE TITLE
Weather icons

### ISSUE THREAD

**Issue by PlayXman** [PlayXman/app-my-spotlight#34]
Let's show current weather as icons. Sun/Moon, clouds, fog, etc.
Right next to temperature.

**Comment by PlayXman** [comment]
Or/and display 3 next hours on hover. And on click open weather.com with prefiltered locality.

**Comment by PlayXman** [comment]
And display the UV level for the current and the next 3 hours forecast.

Resolves #66

**Comment by PlayXman** [comment]
## Technical notes
- Change the API to [One Call API 1.0](https://openweathermap.org/api/one-call-api) with a limit of 1000 calls/day.
- Change the interval of weather updates from 10 minutes to 30 minutes.
- Display the current UV index and weather only on hover. Only the temperature should be visible all the time.
- Display the forecast for the next 3 hours on hover.

## Todo
- [x] Switch to the new One Call API
- [x] New weather widget design
- [x] Link to weather.com
- [x] Fix transition on hover
- [x] Add icons from flaticon.com
- [x] Add thank note to the settings for the icons: [Weather icons created by Good Ware - Flaticon](https://www.flaticon.com/authors/good-ware)
- [x] Update the local DB with new weather model
